project:
  type: website
  output-dir: docs

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

# computational documents should only be re-rendered when source code changes
# see: https://quarto.org/docs/projects/code-execution.html#freeze 
execute:
  freeze: auto 
